version: 2
jobs: 
  publish: 
    working_directory: ~/nodejs-aws-utils
    docker:
      - image: circleci/node:8.10
    steps: 
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm i
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - attach_workspace:
          at: ~/nodejs-aws-utils
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/nodejs-aws-utils/.npmrc
      - run:
          name: Publish package
          command: npm publish


workflows:
  version: 2
  build-publish:
    jobs: 
      - publish:
          filters:
            branches:
              only: 
                - master